; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:vintlabs-devkit-v1]
platform = espressif32
board = vintlabs-devkit-v1
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps = 
    ; bodmer/TFT_eSPI @ ^2.5.43
    madhephaestus/ESP32Encoder @ ^0.10.1
    lovyan03/LovyanGFX @ ^1.1.16

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9488_DRIVER=1
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=15
    -D TFT_DC=26
    -D TFT_RST=4
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D TFT_MISO=19

    -D SMOOTH_FONT=1
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1

    -D ENC_CLK=19
    -D ENC_DT=21
    -D ENC_SW=27